INSERT INTO `video` (`title`,`genre`) VALUES ("lorem, vehicula et, rutrum eu, ultrices"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("convallis dolor.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("consectetuer mauris id sapien. Cras dolor dolor, tempus non,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("enim non nisi. Aenean eget metus."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("hendrerit a, arcu. Sed"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nulla. Integer"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("est ac"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Praesent eu dui. Cum sociis"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("iaculis nec, eleifend"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("adipiscing"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("aliquet, sem ut cursus luctus, ipsum leo elementum"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("elementum sem,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("erat. Vivamus nisi."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dui. Suspendisse ac"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("elit,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Suspendisse ac metus vitae velit egestas lacinia. Sed congue,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("accumsan interdum libero"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nisi magna","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Suspendisse ac metus"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("In ornare sagittis felis. Donec tempor, est ac"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Vestibulum ut eros non enim commodo hendrerit.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("libero. Integer in magna."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("enim,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("arcu et pede. Nunc sed orci lobortis","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("at pretium aliquet, metus urna convallis erat,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("libero lacus, varius et,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ornare placerat, orci lacus vestibulum lorem, sit"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("In tincidunt congue turpis. In condimentum. Donec","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("mi. Aliquam gravida mauris ut mi. Duis risus odio,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lorem tristique aliquet. Phasellus fermentum convallis ligula."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pellentesque eget, dictum placerat, augue."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("eget laoreet posuere, enim nisl elementum purus, accumsan"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("et, commodo at, libero. Morbi accumsan laoreet ipsum."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lectus justo eu arcu. Morbi sit amet massa. Quisque"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("ipsum cursus vestibulum. Mauris"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("urna convallis erat, eget"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("tempor lorem, eget mollis lectus pede et risus."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("sem. Pellentesque ut"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("in faucibus orci luctus"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("non lorem vitae odio sagittis semper. Nam"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("amet, faucibus ut, nulla. Cras eu tellus eu augue"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("adipiscing non, luctus sit amet, faucibus ut, nulla."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lacus. Cras interdum. Nunc sollicitudin commodo","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Proin eget odio. Aliquam vulputate ullamcorper magna."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Ut nec urna et arcu"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("luctus ut, pellentesque eget, dictum placerat,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("mi, ac mattis velit justo nec ante."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dui lectus rutrum urna,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("vehicula"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Morbi sit amet massa. Quisque"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dolor vitae dolor. Donec fringilla."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Cras sed leo. Cras vehicula aliquet libero. Integer in magna.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("tellus","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nonummy. Fusce fermentum fermentum arcu. Vestibulum ante"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lorem fringilla ornare placerat,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("nec tellus. Nunc lectus pede, ultrices","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("quis diam. Pellentesque habitant morbi tristique senectus et"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("ipsum leo"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("quam, elementum at,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("augue"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Ut nec urna et arcu imperdiet ullamcorper. Duis at","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Mauris eu turpis.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("orci lobortis augue scelerisque mollis. Phasellus libero"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Proin dolor. Nulla semper tellus id nunc"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ridiculus mus."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("molestie"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("vitae odio sagittis semper. Nam tempor diam dictum sapien."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("enim. Mauris quis turpis vitae purus gravida sagittis. Duis"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("est"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("augue porttitor interdum. Sed auctor"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lacus. Ut nec urna et arcu imperdiet ullamcorper."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("et nunc. Quisque ornare tortor at risus."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("sem mollis dui, in sodales elit"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("pretium aliquet, metus urna convallis erat, eget tincidunt"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nec ligula consectetuer rhoncus. Nullam velit dui, semper et,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Morbi quis urna. Nunc quis arcu vel quam"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aliquam nec enim. Nunc ut"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nisi magna"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("molestie tellus. Aenean"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aliquam erat"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("lectus pede et risus. Quisque"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Donec nibh. Quisque nonummy"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("conubia nostra, per inceptos hymenaeos."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Fusce mi lorem, vehicula et, rutrum"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("adipiscing non, luctus sit amet, faucibus ut, nulla. Cras","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("facilisis non, bibendum sed, est. Nunc laoreet lectus quis","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Ut nec urna et","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("porttitor eros nec tellus. Nunc lectus pede, ultrices a,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("diam. Proin dolor. Nulla semper tellus id nunc"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pede sagittis augue, eu tempor erat neque"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("cursus in, hendrerit consectetuer, cursus","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("et nunc. Quisque ornare"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("commodo ipsum. Suspendisse non leo. Vivamus nibh"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("luctus et ultrices posuere cubilia","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nisi sem semper"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("venenatis lacus. Etiam"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aliquam erat volutpat. Nulla dignissim. Maecenas ornare"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dictum placerat, augue. Sed molestie. Sed id risus quis diam"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dis parturient montes, nascetur ridiculus mus. Donec dignissim"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("non enim commodo hendrerit. Donec porttitor","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("augue, eu tempor erat neque non"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("eu dolor"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("aliquam"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ante. Vivamus non lorem"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nibh enim, gravida sit amet, dapibus id,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ante blandit viverra. Donec tempus, lorem"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("est ac facilisis","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Nunc sollicitudin"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("libero et tristique pellentesque,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("purus. Duis elementum, dui quis accumsan convallis, ante","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("eu"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nibh sit amet orci. Ut sagittis"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("pretium aliquet, metus urna convallis erat, eget tincidunt"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Cras vulputate velit eu sem. Pellentesque ut ipsum","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nisi magna sed dui. Fusce","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dis parturient montes, nascetur ridiculus mus. Proin vel"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("egestas. Fusce aliquet magna a neque. Nullam ut"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("lacinia.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("molestie in, tempus eu, ligula. Aenean euismod mauris eu elit."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("porttitor eros nec tellus. Nunc lectus pede, ultrices"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Nunc pulvinar arcu et pede. Nunc sed"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nunc, ullamcorper eu, euismod ac, fermentum"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("eget varius ultrices, mauris ipsum porta elit,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("condimentum eget, volutpat ornare, facilisis eget,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lectus convallis est, vitae sodales nisi magna sed"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("purus sapien, gravida non, sollicitudin a, malesuada id,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("metus. In nec orci."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Curabitur vel lectus. Cum sociis natoque"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lacus pede sagittis augue, eu tempor erat","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("adipiscing, enim mi tempor","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("arcu"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("semper, dui lectus rutrum urna, nec luctus","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dolor, nonummy ac, feugiat non, lobortis quis, pede.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ante"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("massa lobortis ultrices."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("senectus et netus et malesuada fames"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("congue turpis. In condimentum.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sem ut cursus luctus, ipsum"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("arcu. Vestibulum ut eros non enim commodo hendrerit."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("fermentum fermentum","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("magna, malesuada vel, convallis in, cursus et,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("at pede. Cras vulputate velit eu sem. Pellentesque","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("at auctor ullamcorper,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Curabitur ut"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nunc est, mollis non, cursus"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("a","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sapien."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Ut nec urna et arcu","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sociis natoque penatibus et magnis dis","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("vitae"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("enim, gravida sit amet,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("mauris elit, dictum eu, eleifend nec, malesuada ut, sem."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("sed pede.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ipsum primis in faucibus orci luctus et ultrices","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("mi. Duis risus odio, auctor vitae,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Vestibulum"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aenean egestas hendrerit neque. In ornare sagittis"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Donec feugiat metus sit amet ante. Vivamus non lorem"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("tempor bibendum. Donec felis","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ornare sagittis"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Duis dignissim tempor arcu. Vestibulum ut eros non enim"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("eu enim."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("cursus vestibulum. Mauris magna. Duis"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("natoque penatibus et magnis dis parturient montes, nascetur"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("amet, faucibus ut, nulla. Cras eu tellus","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Sed diam lorem,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("fermentum metus. Aenean"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("purus gravida sagittis. Duis gravida. Praesent eu nulla"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("dui. Fusce diam nunc, ullamcorper eu, euismod ac,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aenean massa. Integer vitae"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("tellus. Aenean egestas hendrerit neque. In ornare"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sit amet orci. Ut"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("elit, pretium","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Maecenas iaculis aliquet"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("arcu. Nunc mauris. Morbi non sapien molestie"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("vestibulum. Mauris magna.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lacus. Cras","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pharetra. Nam ac nulla."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("turpis vitae purus gravida sagittis."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("et malesuada"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("iaculis quis,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("montes, nascetur ridiculus mus."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("enim, sit amet ornare lectus justo eu arcu.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("laoreet posuere, enim nisl elementum","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("diam lorem, auctor quis, tristique ac,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("feugiat placerat velit. Quisque varius. Nam porttitor","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dapibus"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("sapien. Aenean massa. Integer vitae nibh. Donec est"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("molestie pharetra nibh. Aliquam"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ac mattis semper, dui lectus rutrum urna, nec luctus felis"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ut, nulla. Cras eu tellus eu augue porttitor"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("et, commodo at, libero. Morbi"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Proin nisl sem, consequat nec, mollis vitae,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("sociis natoque penatibus et magnis","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("mattis semper, dui lectus rutrum urna, nec"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aenean euismod mauris eu elit. Nulla","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("egestas."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("eros non enim commodo","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pede. Praesent eu"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("in felis. Nulla tempor augue ac ipsum. Phasellus vitae"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("velit.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("egestas blandit. Nam"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Nunc ullamcorper, velit in aliquet lobortis,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dictum eu, placerat eget, venenatis","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("fringilla cursus purus. Nullam scelerisque"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Proin"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aliquam tincidunt, nunc ac mattis ornare, lectus ante"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("purus ac tellus. Suspendisse"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("massa. Suspendisse eleifend. Cras"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dis"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dictum magna. Ut tincidunt"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("adipiscing lacus. Ut nec urna et arcu imperdiet","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("odio vel est"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Nam nulla magna, malesuada vel, convallis in, cursus et,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ut quam vel"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("malesuada fringilla est."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aenean egestas hendrerit neque. In ornare"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Donec porttitor tellus non magna. Nam ligula elit, pretium"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("lectus sit"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("leo,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("enim"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("parturient montes,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("id, ante. Nunc mauris sapien, cursus in,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("auctor. Mauris vel turpis. Aliquam"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aenean euismod mauris eu elit. Nulla"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("tellus,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("non, lacinia at, iaculis quis,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lobortis risus. In mi pede, nonummy ut, molestie"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("adipiscing non,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("massa. Vestibulum accumsan neque","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("semper erat, in consectetuer ipsum nunc id enim. Curabitur massa."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("non,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nostra, per inceptos hymenaeos. Mauris ut quam vel sapien","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pede, malesuada vel, venenatis vel, faucibus id, libero."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("ac mi eleifend egestas."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aliquam adipiscing lobortis risus. In mi pede,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("egestas, urna justo faucibus lectus, a sollicitudin orci sem"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("dignissim magna a tortor. Nunc commodo auctor"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sit amet risus. Donec egestas. Aliquam","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ipsum primis in faucibus orci luctus et"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("scelerisque sed, sapien."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("in consectetuer ipsum nunc"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nostra, per"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("vel, convallis in, cursus et,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("convallis in,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("nisi. Cum sociis"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("dis parturient"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pharetra. Quisque ac libero nec ligula"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("lacus."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("risus. Duis a mi fringilla mi","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sed tortor. Integer aliquam adipiscing lacus. Ut nec urna"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aliquam rutrum lorem ac risus.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("libero et tristique"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("molestie. Sed id risus quis diam luctus lobortis. Class"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("scelerisque dui. Suspendisse ac"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("magna a neque. Nullam ut"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("risus. Nulla eget metus"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("augue malesuada malesuada. Integer"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ac libero nec ligula consectetuer"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Vestibulum ut eros non enim commodo hendrerit.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("congue a, aliquet vel, vulputate eu, odio. Phasellus"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("commodo"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("lectus ante dictum mi, ac mattis velit justo nec ante."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("erat. Sed nunc"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("erat, eget tincidunt dui"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ipsum. Suspendisse sagittis."," Adventure ");
-- 50 Videos que estan en paquetes, pero los paquetes no estan en ofertas
INSERT INTO `video` (`title`,`genre`) VALUES ("erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("convallis est, vitae sodales nisi magna sed dui."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("sagittis lobortis mauris. Suspendisse aliquet molestie"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dui. Fusce diam nunc, ullamcorper eu,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Integer","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Suspendisse eleifend. Cras sed leo. Cras"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dolor, nonummy ac, feugiat non, lobortis quis, pede."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("a purus."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("sed, sapien. Nunc pulvinar arcu et pede. Nunc sed","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Cras sed leo. Cras","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("mattis semper, dui lectus rutrum urna, nec luctus felis"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("torquent per"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("aliquet magna a neque. Nullam ut nisi a odio","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pede sagittis augue, eu tempor erat neque"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pulvinar arcu et pede. Nunc sed","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("fringilla est."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lorem, sit amet ultricies sem magna nec quam. Curabitur"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("senectus et netus et malesuada fames ac turpis egestas."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("et, commodo at, libero. Morbi accumsan"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("eros","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("egestas nunc sed libero. Proin sed turpis nec"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nascetur ridiculus mus. Proin","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Duis dignissim tempor arcu. Vestibulum ut eros","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("pede, ultrices a, auctor","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("volutpat nunc sit amet metus. Aliquam erat volutpat."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("hendrerit a, arcu. Sed et libero. Proin"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("elit elit fermentum risus,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ut, nulla. Cras"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("porttitor scelerisque neque. Nullam nisl."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("vitae aliquam eros"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Aenean eget metus. In nec orci. Donec"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("arcu. Sed eu nibh"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Class"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("egestas. Fusce aliquet magna a neque. Nullam ut nisi","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("aliquet. Phasellus fermentum convallis ligula. Donec"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nunc. Quisque ornare tortor","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Sed molestie. Sed id risus quis diam","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("et malesuada fames ac"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("at fringilla purus mauris a nunc. In"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("primis in faucibus orci luctus"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Cras eu tellus eu augue porttitor interdum. Sed"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("a, enim. Suspendisse aliquet, sem ut cursus"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("parturient montes, nascetur ridiculus mus. Aenean eget magna."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("fringilla cursus purus. Nullam scelerisque neque sed sem egestas"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ac metus vitae velit egestas lacinia."," Horror");
-- 50 videos que no estan en paquetes, ni en ofertas
INSERT INTO `video` (`title`,`genre`) VALUES ("consectetuer rhoncus. Nullam velit dui,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("blandit enim consequat purus. Maecenas libero est, congue a,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Duis volutpat nunc sit amet metus. Aliquam erat"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("consectetuer euismod est arcu ac orci. Ut semper pretium"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Lorem ipsum dolor sit amet,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("urna justo faucibus lectus, a sollicitudin orci","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sit amet"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("at pretium aliquet, metus urna convallis erat, eget tincidunt dui"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare,","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sagittis. Duis gravida. Praesent"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("purus gravida sagittis. Duis gravida."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sollicitudin orci sem eget massa. Suspendisse eleifend."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("ac","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nulla vulputate dui,"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("enim. Nunc ut erat. Sed nunc est, mollis"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("fringilla. Donec feugiat metus sit amet ante. Vivamus"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("et magnis dis parturient"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("turpis. Nulla aliquet."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Vestibulum ut eros non enim"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("neque","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("arcu iaculis enim, sit amet"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Fusce aliquam, enim nec tempus scelerisque, lorem ipsum"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ad litora torquent"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Nunc quis arcu vel quam dignissim pharetra."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("id, blandit at, nisi. Cum sociis natoque penatibus et magnis"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("elit elit","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("egestas nunc sed libero. Proin sed turpis nec mauris blandit"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("Nullam feugiat placerat velit. Quisque varius. Nam"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec,"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("amet, risus. Donec nibh enim, gravida sit amet, dapibus id,"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Nam ac","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("arcu. Curabitur ut odio vel est tempor"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("facilisis lorem tristique aliquet. Phasellus fermentum convallis"," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("lacus."," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sem egestas blandit."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("sed orci lobortis augue scelerisque mollis. Phasellus libero","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("ultrices iaculis odio. Nam interdum enim non nisi. Aenean"," Adventure ");
INSERT INTO `video` (`title`,`genre`) VALUES ("purus ac tellus. Suspendisse sed dolor.","Action ");
INSERT INTO `video` (`title`,`genre`) VALUES ("magna."," Comedy ");
INSERT INTO `video` (`title`,`genre`) VALUES ("nulla. Cras eu tellus eu augue porttitor interdum."," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("vitae purus gravida sagittis. Duis gravida. Praesent eu"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Proin"," Horror");
INSERT INTO `video` (`title`,`genre`) VALUES ("Proin"," Horror");

-- este video esta en 2 ofertas
INSERT INTO `video` (`title`,`genre`) VALUES ("consequat purus. Maecenas libero est, congue a,"," Adventure ");

